version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0
  poetry: frameio/poetry@0.30.6

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - poetry/install
      - poetry/shell:
          args: pytest
      - codecov/upload:
          file: coverage.xml

workflows:
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
          context: []