#!/usr/bin/env python3

import sys
from pathlib import Path

# Add the project root to the Python path
project_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(project_root))

from src.commit_message_generator import load_and_validate_config, main, CONFIG_FILENAME

if __name__ == '__main__':
    config_file = Path(__file__).resolve().parents[2] / CONFIG_FILENAME
    if not config_file.exists():
        config_file = Path.home() / CONFIG_FILENAME
    config = load_and_validate_config(config_file)
    
    main(config, sys.argv[1])